### PR TITLE
unlock nokogiri so we can do minor updates

### PR DESCRIPTION
**Pull request by grosser**
@arangamani 

I want to use 1.7.x series ...

### CODE REVIEW

**Comment by grosser** [comment]
`An error occurred while installing jeweler (2.3.2), and Bundler cannot continue.`

... want a PR to remove jeweler ?

**Comment by grosser** [comment]
@arangamani if you don't maintain this anymore, add me as maintainer ?

**Comment by st33b** [comment]
Seconding this PR. `jenkins_api_client` is the only thing holding us back from updating Nokogiri to 1.7.*. Thanks!

**Comment by grosser** [comment]
@arangamani can you add another maintainer or merge/release this ?

**Comment by grosser** [comment]
❤️

**Comment by arangamani** [comment]
Gem version [1.5.2](https://rubygems.org/gems/jenkins_api_client/versions/1.5.2) is released.

**Comment by grosser** [comment]
oh, you already did :D

**Comment by grosser** [comment]
here https://github.com/arangamani/jenkins_api_client/pull/230

**Pull request merged**
