### PR TITLE
add a list_jobs_with_details() method for listing jobs for a given view with details

### PR DESCRIPTION
**Pull request by Tyrael**
let me know if I missed/screwed up something

### CODE REVIEW

**Comment by Tyrael** [comment]
ping @arangamani

**Comment by arangamani** [comment]
Sorry for the delay @Tyrael I'll get to it this weekend.

**Comment by Tyrael** [comment]
@arangamani thanks!

**Comment by Tyrael** [comment]
hi, any chance you had time to look into this?

**Comment by arangamani** [comment]
Released as `v1.4.2` now.

**Comment by Tyrael** [comment]
Kudos

**Pull request merged**
