### PR TITLE
Fix for is_offline? bug reporting all nodes as being offline

### PR DESCRIPTION
**Pull request by bsnape**
Hi,

This is a fix related to #164.

Please let me know what you think and if you'd like any changes to be made.

Ben

### CODE REVIEW

**Comment by arangamani** [comment]
Sorry for the delay in getting to this PR. I believe I used to get a string when I initially wrote that code. It is great if we get a boolean but I just wanted to make sure we shouldn't break any backwards compatibility with this change. We could either confirm if this behavior was not changed recently by Jenkins or check for both types. What do you think?

**Comment by bsnape** [comment]
Hey, thanks for getting back to me. No problem regarding the wait - I ended up using the Jenkins API directly for my very simple use case. 

Yeah I find it hard to believe that you overlooked this when you wrote this gem originally so I'm sure the API has changed in the interim. I was testing against a recent Jenkins version (`~1.590`) so I'm not sure about older versions but I could investigate it. 

Like you mentioned, a more practical approach for now might be to change my PR to accept a string or boolean.

I think moving forward it might be a good idea to have more explicit templated API responses for use in your unit tests - obviously these require some upkeep to prevent API drift which might be costly in terms of time. Ultimately I suppose it depends how invested you want to be as the Jenkins API changes. 

Ben

**Comment by bsnape** [comment]
Hi @arangamani, can we consider merging @luchenghan's changes? Both strings and booleans are now supported like we discussed above (sorry I forgot to come back and finish this).

**Comment by arangamani** [comment]
@bsnape Sure!

**Comment by arangamani** [comment]
I'll release a new version in a day or two. Thanks all!

**Comment by luchenghan** [comment]
Wonderful! Thanks @bsnape and @arangamani !

**Pull request merged**
